import { fileURLToPath } from 'url';
import path from 'path';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
import Pharmacy from "../models/Pharmacy.js";
import bcrypt from "bcryptjs";
// hms-backend/routes/staffWork.js
// Add to server.js:  app.use('/api/staff-work', require('./routes/staffWork'));

import express from 'express';
const router  = express.Router();
const {auth}    = require('../middleware/auth');

import Billing  from '../models/Billing.js';
import Lab      from '../models/Lab.js';
import Token    from '../models/Token.js';
import Patient  from '../models/Patient.js';

/**
 * Resolves clinicId from (in priority order):
 *  1. req.query.clinicId  — GET requests pass it as a query param
 *  2. req.user.clinicId   — set by the auth middleware from the JWT
 *  3. 'default'           — safe fallback
 */
function resolveClinicId(req) {
  return req.query?.clinicId || req.user?.clinicId || 'default';
}

// ── Helper: today's date range ────────────────────────────────────────────────
function todayRange() {
  const start = new Date(); start.setHours(0,  0,  0,   0);
  const end   = new Date(); end.setHours(23, 59, 59, 999);
  return { start, end };
}

function todayStr() {
  const d   = new Date();
  const yr  = d.getFullYear();
  const mo  = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${yr}-${mo}-${day}`;
}

// ── GET /api/staff-work/:userId  ──────────────────────────────────────────────
// Returns today's work summary for a specific staff member.
// Admin-only endpoint.
router.get('/:userId', auth, async (req, res) => {
  try {
    const clinicId         = resolveClinicId(req);
    const { userId }       = req.params;
    const { start, end }   = todayRange();
    const date             = todayStr();
    const dateFilter       = { $gte: start, $lte: end };

    // ── 1. BILLING — bills generated by this user today ───────────────────────
    const billsToday = await Billing.find({
      clinicId,
      generatedBy: userId,
      createdAt:   dateFilter,
    }).populate('patient', 'name patientId');

    const billingRevenue = billsToday
      .filter(b => b.paymentStatus === 'Paid')
      .reduce((sum, b) => sum + (b.totalAmount || 0), 0);
    const billingPending = billsToday.filter(b => b.paymentStatus === 'Pending').length;
    const billingPaid    = billsToday.filter(b => b.paymentStatus === 'Paid').length;

    // ── 2. TOKENS — tokens generated by this user today ───────────────────────
    const tokensToday = await Token.find({
      clinicId,
      generatedBy: userId,
      date,
    }).populate('patient', 'name patientId')
      .populate('doctor',  'name department');

    const tokensDone    = tokensToday.filter(t => t.status === 'Done').length;
    const tokensWaiting = tokensToday.filter(t => t.status === 'Waiting').length;
    const tokensSkipped = tokensToday.filter(t => t.status === 'Skipped').length;

    // ── 3. DOCTOR TOKENS — if this user IS a doctor, tokens assigned to them ──
    const doctorTokensToday = await Token.find({
      clinicId,
      doctor: userId,
      date,
    }).populate('patient', 'name patientId');

    const doctorTokensDone    = doctorTokensToday.filter(t => t.status === 'Done').length;
    const doctorTokensWaiting = doctorTokensToday.filter(t => t.status === 'Waiting').length;

    // ── 4. LAB — tests ordered by this user today ────────────────────────────
    const labsToday = await Lab.find({
      clinicId,
      orderedBy: userId,
      createdAt: dateFilter,
    }).populate('patient', 'name patientId');

    const labRevenue   = labsToday.reduce((sum, l) => sum + (l.totalAmount || 0), 0);
    const labCompleted = labsToday.filter(l => l.status === 'Completed').length;
    const labPending   = labsToday.filter(l => l.status !== 'Completed' && l.status !== 'Cancelled').length;

    // ── 5. PATIENTS registered today (clinic-scoped) ─────────────────────────
    const patientsRegisteredToday = await Patient.countDocuments({
      clinicId,
      createdAt: dateFilter,
    });

    // ── 6. PHARMACY — prescriptions dispensed by this user today ─────────────
    let pharmacyToday   = [];
    let pharmacyRevenue = 0;
    try {
      pharmacyToday   = await Pharmacy.find({
        clinicId,
        dispensedBy: userId,
        createdAt:   dateFilter,
      }).populate('patient', 'name patientId');
      pharmacyRevenue = pharmacyToday.reduce((sum, p) => sum + (p.totalAmount || 0), 0);
    } catch {
      // Pharmacy model may not exist — skip silently
    }

    // ── Assemble response ─────────────────────────────────────────────────────
    res.json({
      date,
      billing: {
        total:   billsToday.length,
        paid:    billingPaid,
        pending: billingPending,
        revenue: billingRevenue,
        bills:   billsToday.slice(0, 10),
      },
      tokens: {
        generated: tokensToday.length,
        done:      tokensDone,
        waiting:   tokensWaiting,
        skipped:   tokensSkipped,
        list:      tokensToday.slice(0, 10),
      },
      doctorTokens: {
        total:   doctorTokensToday.length,
        done:    doctorTokensDone,
        waiting: doctorTokensWaiting,
        list:    doctorTokensToday.slice(0, 10),
      },
      lab: {
        total:     labsToday.length,
        completed: labCompleted,
        pending:   labPending,
        revenue:   labRevenue,
        list:      labsToday.slice(0, 10),
      },
      pharmacy: {
        total:   pharmacyToday.length,
        revenue: pharmacyRevenue,
        list:    pharmacyToday.slice(0, 10),
      },
      patients: {
        registeredToday: patientsRegisteredToday,
      },
      totalRevenueToday: billingRevenue + labRevenue + pharmacyRevenue,
    });
  } catch (err) {
    console.error('Staff work error:', err);
    res.status(500).json({ message: err.message });
  }
});

export default router;